# Generated by Django 4.2.11 on 2026-02-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashram', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
